import { Printer, PrinterStatus, PrinterType, User, UserRole, Site } from './types';

export const MOCK_SITES: Site[] = [
  { id: 'site-001', name: 'Unidade Fabril', description: 'Fábrica Principal' },
  { id: 'site-002', name: 'Escritório Central', description: 'Sede Administrativa' },
  { id: 'site-003', name: 'Centro de Distribuição', description: 'Logística e Expedição' }
];

export const MOCK_USERS: User[] = [
  {
    id: 'usr-001',
    name: 'Admin Principal',
    email: 'admin@printhub.com',
    role: UserRole.ADMIN,
    lastLogin: new Date().toISOString()
  },
  {
    id: 'usr-002',
    name: 'Analista de Suporte',
    email: 'analista@printhub.com',
    role: UserRole.ANALYST,
    site: 'Unidade Fabril',
    lastLogin: new Date(Date.now() - 43200000).toISOString()
  },
  {
    id: 'usr-003',
    name: 'Operador Padrão',
    email: 'operador@printhub.com',
    role: UserRole.USER,
    site: 'Unidade Fabril',
    lastLogin: new Date(Date.now() - 86400000).toISOString()
  },
  {
    id: 'usr-004',
    name: 'Gerente CD',
    email: 'gerente.cd@printhub.com',
    role: UserRole.ANALYST,
    site: 'Centro de Distribuição',
    lastLogin: new Date(Date.now() - 12000000).toISOString()
  }
];

export const MOCK_PRINTERS: Printer[] = [
{
    id: 'prt-001',
    name: 'PAPEL BP4',
    manufacturer: 'Datamax',
    model: 'I-4212',
    type: PrinterType.THERMAL,
    serialNumber: '52253346',
    assetId: 'DXIT-0000600',
    site: 'Unidade Fabril',
    location: 'MER - PAPEL BP4',
    ipAddress: '10.154.47.12',
    queueName: '\\10.154.47.12\LAMIBP4_P02',
    status: PrinterStatus.ONLINE,
    lastUpdated: new Date().toISOString(),
    notes: ''
  },
  {
    id: 'prt-002',
    name: 'IMPREGNADORA',
    manufacturer: 'Zebra',
    model: 'ZT411',
    type: PrinterType.THERMAL,
    serialNumber: '99N223400843',
    assetId: 'DXIT-0005732',
    site: 'Unidade Fabril',
    location: 'MER - IMPREGNADORA',
    ipAddress: '10.154.47.18',
    queueName: '\\10.154.47.18\IMPREG1_P01',
    status: PrinterStatus.ONLINE,
    lastUpdated: new Date().toISOString(),
    notes: ''
  },
  {
    id: 'prt-003',
    name: 'PLASTIFICADORA',
    manufacturer: 'Datamax',
    model: 'W-6208',
    type: PrinterType.THERMAL,
    serialNumber: '30578007',
    assetId: 'DXBT-0219849',
    site: 'Unidade Fabril',
    location: 'MER - PLASTIFICADORA',
    ipAddress: '10.154.47.21',
    queueName: '\\10.154.47.21\PLASTIF_P02',
    status: PrinterStatus.ONLINE,
    lastUpdated: new Date().toISOString(),
    notes: ''
  },
  {
    id: 'prt-004',
    name: 'REEMBALAGEM',
    manufacturer: 'Datamax',
    model: 'W-6208',
    type: PrinterType.THERMAL,
    serialNumber: '24878016',
    assetId: 'DXIT-0305982',
    site: 'Unidade Fabril',
    location: 'MER - REEMBALAGEM',
    ipAddress: '10.154.47.22',
    queueName: '\\10.154.47.22\REEMBA_P01',
    status: PrinterStatus.ONLINE,
    lastUpdated: new Date().toISOString(),
    notes: ''
  },
  {
    id: 'prt-005',
    name: 'AE',
    manufacturer: 'Zebra',
    model: 'ZT420',
    type: PrinterType.THERMAL,
    serialNumber: '18J173105997',
    assetId: 'DXIT-0005737',
    site: 'Unidade Fabril',
    location: 'MDF - AE',
    ipAddress: '10.154.6.19',
    queueName: '\\dxitimp02\QT11',
    status: PrinterStatus.ONLINE,
    lastUpdated: new Date().toISOString(),
    notes: ''
  },
  {
    id: 'prt-006',
    name: 'PRENSA BP3',
    manufacturer: 'Zebra',
    model: 'ZT411',
    type: PrinterType.THERMAL,
    serialNumber: '99N223401322',
    assetId: 'DXIT-0005682',
    site: 'Unidade Fabril',
    location: 'MER - PRENSA BP3',
    ipAddress: '10.154.6.20',
    queueName: '\\dxitimp02\QT10',
    status: PrinterStatus.ONLINE,
    lastUpdated: new Date().toISOString(),
    notes: ''
  },
  {
    id: 'prt-007',
    name: 'HIGH GLOSS',
    manufacturer: 'Datamax',
    model: 'W-6208',
    type: PrinterType.THERMAL,
    serialNumber: '53278139',
    assetId: 'DXIT-0151743',
    site: 'Unidade Fabril',
    location: 'MER - HIGH GLOSS',
    ipAddress: '10.154.6.22',
    queueName: '\\dxitimp02\QT08',
    status: PrinterStatus.ONLINE,
    lastUpdated: new Date().toISOString(),
    notes: ''
  },
  {
    id: 'prt-008',
    name: 'PRENSA BP2',
    manufacturer: 'Zebra',
    model: 'ZT411',
    type: PrinterType.THERMAL,
    serialNumber: '99N223401313',
    assetId: 'DXIT-0005733',
    site: 'Unidade Fabril',
    location: 'MER - PRENSA BP2',
    ipAddress: '10.154.6.23',
    queueName: '\\dxitimp02\QT07',
    status: PrinterStatus.ONLINE,
    lastUpdated: new Date().toISOString(),
    notes: ''
  },
  {
    id: 'prt-009',
    name: 'ALMOXARIFADO',
    manufacturer: 'Zebra',
    model: 'ZT411',
    type: PrinterType.THERMAL,
    serialNumber: '99N223400808',
    assetId: 'DXIT-0005734',
    site: 'Unidade Fabril',
    location: 'ALMOXARIFADO',
    ipAddress: '10.154.6.24',
    queueName: '\\dxitimp02\QT06',
    status: PrinterStatus.ONLINE,
    lastUpdated: new Date().toISOString(),
    notes: ''
  },
  {
    id: 'prt-010',
    name: 'EMBALAGEM MDP',
    manufacturer: 'Zebra',
    model: 'ZT420',
    type: PrinterType.THERMAL,
    serialNumber: '18J173105996',
    assetId: 'DXIT-0005738',
    site: 'Unidade Fabril',
    location: 'MDP - EMBALAGEM',
    ipAddress: '10.154.6.25',
    queueName: '\\dxitimp02\QT05',
    status: PrinterStatus.ONLINE,
    lastUpdated: new Date().toISOString(),
    notes: ''
  },
  {
    id: 'prt-011',
    name: 'ITPACK 01',
    manufacturer: 'Honeywell',
    model: 'PX65',
    type: PrinterType.THERMAL,
    serialNumber: '12322565092',
    assetId: 'DXIT-1589726',
    site: 'Unidade Fabril',
    location: 'MER - ITPACK 01',
    ipAddress: '10.154.6.28',
    queueName: '\\dxitimp02\QT03',
    status: PrinterStatus.ONLINE,
    lastUpdated: new Date().toISOString(),
    notes: ''
  },
  {
    id: 'prt-012',
    name: 'EMBALAGEM MDF',
    manufacturer: 'Honeywell',
    model: 'PX65',
    type: PrinterType.THERMAL,
    serialNumber: '12322565093',
    assetId: 'DXIT-1589727',
    site: 'Unidade Fabril',
    location: 'MDF - EMBALAGEM',
    ipAddress: '10.154.6.27',
    queueName: '\\dxitimp02\QT02',
    status: PrinterStatus.ONLINE,
    lastUpdated: new Date().toISOString(),
    notes: ''
  },
  {
    id: 'prt-013',
    name: 'ITPACK 02',
    manufacturer: 'Zebra',
    model: 'ZT420',
    type: PrinterType.THERMAL,
    serialNumber: '18J173105995',
    assetId: 'DXIT-0005687',
    site: 'Unidade Fabril',
    location: 'MER - ITPACK 02',
    ipAddress: '10.154.6.26',
    queueName: '\\dxitimp02\QT01',
    status: PrinterStatus.ONLINE,
    lastUpdated: new Date().toISOString(),
    notes: ''
  },
  {
    id: 'prt-014',
    name: 'MERCADO EXTERNO',
    manufacturer: 'Zebra',
    model: 'ZT421',
    type: PrinterType.THERMAL,
    serialNumber: '99N220600064',
    assetId: 'DXIT-0005283',
    site: 'Unidade Fabril',
    location: 'MDF - MERCADO EXTERNO',
    ipAddress: '10.154.6.29',
    queueName: '\\dxitimp02\QT04',
    status: PrinterStatus.ONLINE,
    lastUpdated: new Date().toISOString(),
    notes: ''
  },
  {
    id: 'prt-015',
    name: 'EXPEDIÇÃO CD 1',
    manufacturer: 'Zebra',
    model: 'ZT411',
    type: PrinterType.THERMAL,
    serialNumber: '99N220600099',
    assetId: 'DXIT-0009999',
    site: 'Centro de Distribuição',
    location: 'EXPEDIÇÃO',
    ipAddress: '10.154.50.10',
    queueName: '\\dxitimp03\CD_EXP_01',
    status: PrinterStatus.ONLINE,
    lastUpdated: new Date().toISOString(),
    notes: ''
  }
];
